name: Publish Release Artifacts

on:
  release:
    types: [published]

jobs:
  github-release-assets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build main jar
      run: ./gradlew build
    - name: Upload main jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./build/libs/CASprzak.jar
        asset_name: CASprzak-${{ github.event.release.tag_name }}.jar
        asset_content_type: application/java-archive
    - name: Upload cas.properties
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./core/src/java/show/ezkz/casprzak/core/config/cas.properties
        asset_name: cas.properties
        asset_content_type: text/plain
  maven-central:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Publish to Maven Central
      run: ./gradlew publish closeAndReleaseRepository
      env:
        ORG_GRADLE_PROJECT_mavenUsername: ${{ secrets.mavenUsername }}
        ORG_GRADLE_PROJECT_mavenPassword: ${{ secrets.mavenPassword }}
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.signingKey }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.signingPassword }}
